services:
  postgres:
    image: postgres:13
    volumes:
      - ./pg_data/:/var/lib/postgresql/data
    env_file:
      - django_api/movies_admin/config/.env
    networks:
      - yandex_django
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  django_app:
    build:
      context: django_api/movies_admin
    volumes:
      - static/:/app/static/
    env_file:
      - django_api/movies_admin/config/.env
    networks:
      - yandex_django
    depends_on:
        postgres:
          condition: service_healthy

  nginx:
    image: nginx:latest
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - static/:/opt/app/static/
    depends_on:
      - django_app
    networks:
      - yandex_django
    ports:
      - "80:80"

volumes:
  static:

networks:
    yandex_django:
