# Generated by Django 3.2 on 2022-11-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20221125_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='file_path',
            new_name='file_path_somewhere',
        ),
    ]
