# Generated by Django 3.2 on 2022-12-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_file_path_somewhere_filmwork_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='certificate',
        ),
    ]
